[project]
name = "muvue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eugene Kim", email = "eugkim0120@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "typer>=0.27.2",
    "uvicorn[standard]>=0.53.0",
]
license = "MIT"

[project.scripts]
muvue = "muvue.cli.main:main"
muvue-fake-agent = "muvue.fake_agent:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
